name: CI

on:
  push:
    branches:
      - main
      - master
      - workflows
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x.x

    - name: Restore tool
      run: dotnet tool restore

    - name: Check Format
      run: dotnet fsi build.fsx -t format.check

    - name: Build (Debug)
      run: dotnet build

    - name: Test
      run: dotnet test Test
